# Generated by Django 3.2 on 2023-02-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230219_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ['-id']},
        ),
    ]
